name: format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt-get install clang-format-16

    - name: Check format
      run: |
        clang-format-16 --dry-run --Werror *.c genimage.h
